package controllers

import (
	"aicodeium/initializers"
	"aicodeium/models"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

type classroomResponse struct {
	ID          uint   `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	TeacherID   uint   `json:"teacher_id"`
	TeacherName string `json:"teacher_name"`
	InviteCode  string `json:"invite_code"`
	Archived    bool   `json:"archived"`
	CreatedAt   string `json:"created_at"`
}

func CreateClassroom(c *gin.Context) {
	// Get teacher info from JWT middleware
	teacherId := c.GetUint("userID")
	teacherRole := c.GetString("role")

	if teacherRole != "teacher" {
		c.JSON(http.StatusForbidden, gin.H{
			"error": "Only teachers can create classrooms",
		})
		return
	}

	// Bind request body
	var body struct {
		Name        string `json:"name" binding:"required"`
		Description string `json:"description"`
	}

	if err := c.ShouldBindJSON(&body); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{
			"error": err.Error(),
		})
		return
	}

	// Get teachers name from database
	var teacher models.User
	if err := initializers.DB.First(&teacher, teacherId).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{
			"error": "Teacher not found",
		})
		return
	}

	// Create classroom
	classroom := models.Classroom{
		Name:        body.Name,
		Description: body.Description,
		TeacherID:   teacherId,
		TeacherName: teacher.Name,
		// InviteCode will be auto-generated by BeforeCreate hook
	}

	result := initializers.DB.Create(&classroom)
	if result.Error != nil {
		c.JSON(http.StatusInternalServerError, gin.H{
			"error": "Failed to create classroom",
		})
		return
	}

	c.JSON(http.StatusCreated, gin.H{
		"id":           classroom.ID,
		"name":         classroom.Name,
		"description":  classroom.Description,
		"teacher_id":   classroom.TeacherID,
		"teacher_name": classroom.TeacherName,
		"invite_code":  classroom.InviteCode,
		"archived":     classroom.Archived,
		"created_at":   classroom.CreatedAt.Format(time.RFC3339),
	})
}

func GetClassrooms(c *gin.Context) {
	userID := c.GetUint("userID")
	userRole := c.GetString("role")

	classrooms := []models.Classroom{}
	var query *gorm.DB

	if userRole == "teacher" {
		// Teacher see their own created classrooms
		query = initializers.DB.Where("teacher_id = ? AND archived = ?", userID, false)
	} else if userRole == "student" {
		// Students see classrooms they are enrolled in
		query = initializers.DB.
			Table("classrooms").
			Joins("JOIN enrollments ON enrollments.classroom_id = classrooms.id").
			Where("enrollments.student_id = ? AND classrooms.archived = ?", userID, false)
	} else {
		c.JSON(http.StatusForbidden, gin.H{
			"error": "Invalid role",
		})
		return
	}

	if err := query.Find(&classrooms).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{
			"error": "Failed to fetch classrooms",
		})
		return
	}

	result := make([]classroomResponse, 0, len(classrooms))
	for _, cr := range classrooms {
		result = append(result, classroomResponse{
			ID:          cr.ID,
			Name:        cr.Name,
			Description: cr.Description,
			TeacherID:   cr.TeacherID,
			TeacherName: cr.TeacherName,
			InviteCode:  cr.InviteCode,
			Archived:    cr.Archived,
			CreatedAt:   cr.CreatedAt.Format(time.RFC3339),
		})
	}
	c.JSON(http.StatusOK, result)
}

func GetClassroomByID(c *gin.Context) {
	id := c.Param("id")
	userID := c.GetUint("userID")
	userRole := c.GetString("role")

	var classroom models.Classroom

	// Find the classroom
	if err := initializers.DB.First(&classroom, id).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{
			"error": "Classroom not found",
		})
		return
	}

	// check access permission
	if userRole == "student" {
		var enrollment models.Enrollment
		if err := initializers.DB.
			Where("classroom_id = ? AND student_id = ?", classroom.ID, userID).
			First(&enrollment).Error; err != nil {
			c.JSON(http.StatusForbidden, gin.H{
				"error": "You are not enrolled in this classroom",
			})
			return
		}
	} else if userRole == "teacher" {
		// Teacher must own the classroom
		if classroom.TeacherID != userID {
			c.JSON(http.StatusForbidden, gin.H{
				"error": "You don't own this classroom",
			})
			return
		}
	} else {
		c.JSON(http.StatusForbidden, gin.H{
			"error": "invalid role",
		})
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"id":           classroom.ID,
		"name":         classroom.Name,
		"description":  classroom.Description,
		"teacher_id":   classroom.TeacherID,
		"teacher_name": classroom.TeacherName,
		"invite_code":  classroom.InviteCode,
		"archived":     classroom.Archived,
		"created_at":   classroom.CreatedAt.Format(time.RFC3339),
	})
}

func GetClassroomByCode(c *gin.Context) {
	code := c.Param("code")

	var classroom models.Classroom
	if err := initializers.DB.Where("invite_code = ?", code).First(&classroom).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{
			"error": "Classroom not found with this invite code",
		})
		return
	}

	if classroom.Archived {
		c.JSON(http.StatusForbidden, gin.H{
			"error": "This classroom is archived",
		})
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"id":           classroom.ID,
		"name":         classroom.Name,
		"description":  classroom.Description,
		"teacher_name": classroom.TeacherName,
		"invite_code":  classroom.InviteCode,
		"archived":     false,
	})
}
